// java.sql.* — JDBC connection/statement/result-set types and the
// java.sql.rowset sub-namespace.

declare namespace java {
  namespace sql {
    /**
     * A connection (session) with a specific database.
     */
    interface Connection {
      /** Releases this Connection object's database and JDBC resources immediately. */
      close(): void;

      /** Makes all changes made since the previous commit/rollback permanent. */
      commit(): void;

      /** Undoes all changes made in the current transaction. */
      rollback(): void;

      /** Sets this connection's auto-commit mode to the given state. */
      setAutoCommit(autoCommit: boolean): void;

      /** Retrieves the current auto-commit mode for this Connection object. */
      getAutoCommit(): boolean;

      /** Retrieves whether this Connection object has been closed. */
      isClosed(): boolean;

      /** Creates a Statement object for sending SQL statements to the database. */
      createStatement(): Statement;

      /** Creates a PreparedStatement object for sending parameterized SQL statements to the database. */
      prepareStatement(sql: java.lang.String): PreparedStatement;
    }

    /**
     * The interface that every driver class must implement.
     */
    interface Driver {
      /** Attempts to make a database connection to the given URL. */
      connect(url: java.lang.String, info: java.util.Properties): Connection;

      /** Retrieves whether the driver thinks that it can open a connection to the given URL. */
      acceptsURL(url: java.lang.String): boolean;
    }

    /**
     * An object used for executing a static SQL statement and returning the results it produces.
     */
    interface Statement {
      /** Executes the given SQL statement, which returns a single ResultSet object. */
      executeQuery(sql: java.lang.String): ResultSet;

      /** Executes the given SQL statement, which may be an INSERT, UPDATE, or DELETE statement. */
      executeUpdate(sql: java.lang.String): int;

      /** Releases this Statement object's database and JDBC resources immediately. */
      close(): void;
    }

    /**
     * An object that represents a precompiled SQL statement.
     */
    interface PreparedStatement extends Statement {
      /** Sets the designated parameter to the given Java object. */
      setObject(parameterIndex: int, x: java.lang.Object): void;

      /** Executes the SQL query in this PreparedStatement object and returns the ResultSet object generated by the query. */
      executeQuery(): ResultSet;

      /** Executes the SQL statement in this PreparedStatement object. */
      executeUpdate(): int;
    }

    /**
     * A table of data representing a database result set.
     */
    interface ResultSet {
      /** Moves the cursor forward one row from its current position. */
      next(): boolean;

      /** Retrieves the value of the designated column as a String. */
      getString(columnLabel: java.lang.String): java.lang.String;

      getString(columnIndex: int): java.lang.String;

      /** Retrieves the value of the designated column as an int. */
      getInt(columnLabel: java.lang.String): int;

      getInt(columnIndex: int): int;

      /** Retrieves the value of the designated column as an Object. */
      getObject(columnLabel: java.lang.String): java.lang.Object;

      getObject(columnIndex: int): java.lang.Object;

      /** Releases this ResultSet object's database and JDBC resources immediately. */
      close(): void;
    }

    /**
     * An exception that provides information on a database access error or other errors.
     */
    class SQLException extends java.lang.Exception {
      constructor();
      constructor(reason: java.lang.String);
      constructor(reason: java.lang.String, sqlState: java.lang.String);
      constructor(reason: java.lang.String, sqlState: java.lang.String, vendorCode: int);
      constructor(cause: java.lang.Throwable);
    }

    /**
     * Reports a warning on a database access.
     */
    class SQLWarning extends SQLException {
      constructor();
      constructor(reason: java.lang.String);
      /** Retrieves the warning chained to this SQLWarning object. */
      getNextWarning(): SQLWarning;
    }

    /**
     * The representation (mapping) in the Java programming language of an SQL DATE value.
     */
    class Date extends java.util.Date {
      constructor(date: long);
      static valueOf(s: java.lang.String): Date;
    }

    /**
     * The representation (mapping) in the Java programming language of an SQL TIME value.
     */
    class Time extends java.util.Date {
      constructor(time: long);
      static valueOf(s: java.lang.String): Time;
    }

    /**
     * The representation (mapping) in the Java programming language of an SQL TIMESTAMP value.
     */
    class Timestamp extends java.util.Date {
      constructor(time: long);
      static valueOf(s: java.lang.String): Timestamp;
      getNanos(): int;
      setNanos(n: int): void;
    }

    /**
     * The representation of a savepoint, a point within the current transaction
     * that can be referenced from the rollback method.
     */
    interface Savepoint {
      /** Retrieves the generated ID for the savepoint. */
      getSavepointId(): int;
      /** Retrieves the name of the savepoint. */
      getSavepointName(): java.lang.String;
    }

    /**
     * The mapping in the Java programming language of an SQL REF value.
     */
    interface Ref {
      /** Retrieves the fully-qualified SQL name of the SQL structured type. */
      getBaseTypeName(): java.lang.String;
      /** Retrieves the referenced object. */
      getObject(): java.lang.Object;
      getObject(map: java.util.Map<java.lang.String, java.lang.Class<any>>): java.lang.Object;
    }

    /**
     * The representation (mapping) in the Java programming language of an SQL BLOB value.
     */
    interface Blob {
      /** Returns the number of bytes in the BLOB value. */
      length(): long;
      /** Retrieves all or part of the BLOB value as a byte array. */
      getBytes(pos: long, length: int): byte[];
      /** Retrieves the BLOB value as a stream. */
      getBinaryStream(): java.io.InputStream;
      getBinaryStream(pos: long, length: long): java.io.InputStream;
    }

    /**
     * The mapping in the Java programming language of an SQL CLOB value.
     */
    interface Clob {
      /** Retrieves the number of characters in the CLOB value. */
      length(): long;
      /** Retrieves a copy of the specified substring. */
      getSubString(pos: long, length: int): java.lang.String;
      /** Retrieves the CLOB value as a character stream. */
      getCharacterStream(): java.io.Reader;
      getCharacterStream(pos: long, length: long): java.io.Reader;
      /** Retrieves the CLOB value as an ascii stream. */
      getAsciiStream(): java.io.InputStream;
    }

    /**
     * The mapping in the Java programming language of an SQL NCLOB value.
     */
    interface NClob extends Clob {}

    /**
     * The mapping in the Java programming language for the SQL type ARRAY.
     */
    interface Array {
      /** Retrieves the SQL type name of the elements in the array. */
      getBaseTypeName(): java.lang.String;
      /** Retrieves the JDBC type of the elements in the array. */
      getBaseType(): int;
      /** Retrieves the contents of the SQL ARRAY value as a Java array. */
      getArray(): java.lang.Object;
      getArray(map: java.util.Map<java.lang.String, java.lang.Class<any>>): java.lang.Object;
      /** Retrieves a result set containing the elements of the array. */
      getResultSet(): ResultSet;
      getResultSet(map: java.util.Map<java.lang.String, java.lang.Class<any>>): ResultSet;
    }

    /**
     * The representation (mapping) in the Java programming language of an SQL ROWID value.
     */
    interface RowId {
      /** Returns an array of bytes representing the value of the SQL ROWID. */
      getBytes(): byte[];
    }

    /**
     * The mapping in the Java programming language for the SQL XML type.
     */
    interface SQLXML {
      /** Retrieves the XML value as a String. */
      getString(): java.lang.String;
      /** Sets the XML value for this SQLXML instance. */
      setString(value: java.lang.String): void;
      /** Retrieves a stream to read the XML value. */
      getBinaryStream(): java.io.InputStream;
      /** Retrieves the XML value as a character stream. */
      getCharacterStream(): java.io.Reader;
      /** Frees the XML value that this object represents. */
      free(): void;
    }

    /**
     * An object that can be used to get information about the types and properties
     * of the columns in a ResultSet object.
     */
    interface ResultSetMetaData {
      /** Returns the number of columns in this ResultSet object. */
      getColumnCount(): int;
      /** Gets the designated column's table's catalog name. */
      getCatalogName(column: int): java.lang.String;
      /** Returns the fully-qualified name of the Java class to which values will be mapped. */
      getColumnClassName(column: int): java.lang.String;
      /** Indicates the designated column's normal maximum width in characters. */
      getColumnDisplaySize(column: int): int;
      /** Gets the designated column's suggested title for use in printouts. */
      getColumnLabel(column: int): java.lang.String;
      /** Get the designated column's name. */
      getColumnName(column: int): java.lang.String;
      /** Retrieves the designated column's SQL type. */
      getColumnType(column: int): int;
      /** Retrieves the designated column's database-specific type name. */
      getColumnTypeName(column: int): java.lang.String;
      /** Get the designated column's table's schema. */
      getSchemaName(column: int): java.lang.String;
      /** Gets the designated column's table name. */
      getTableName(column: int): java.lang.String;
      /** Indicates whether the designated column is automatically numbered. */
      isAutoIncrement(column: int): boolean;
      /** Indicates whether a column's case matters. */
      isCaseSensitive(column: int): boolean;
      /** Indicates whether the designated column is definitely not writable. */
      isReadOnly(column: int): boolean;
      /** Indicates whether the designated column can be used in a WHERE clause. */
      isSearchable(column: int): boolean;
      /** Indicates whether values in the designated column are signed numbers. */
      isSigned(column: int): boolean;
      /** Indicates whether it is possible for a write on the designated column to succeed. */
      isWritable(column: int): boolean;
      /** Indicates the nullability of values in the designated column. */
      isNullable(column: int): int;
      /** Gets the designated column's specified column size. */
      getPrecision(column: int): int;
      /** Gets the designated column's number of digits to right of the decimal point. */
      getScale(column: int): int;
    }

    /**
     * An object that contains information about the columns in a RowSet object.
     */
    interface RowSetMetaData extends ResultSetMetaData {
      /** Sets the number of columns in the RowSet object. */
      setColumnCount(columnCount: int): void;
      /** Sets whether the designated column is automatically numbered. */
      setAutoIncrement(columnIndex: int, property: boolean): void;
      /** Sets whether the designated column is case sensitive. */
      setCaseSensitive(columnIndex: int, property: boolean): void;
      /** Sets whether the designated column can be used in a WHERE clause. */
      setSearchable(columnIndex: int, property: boolean): void;
      /** Sets whether the designated column is a cash value. */
      setCurrency(columnIndex: int, property: boolean): void;
      /** Sets whether the designated column's value can be set to NULL. */
      setNullable(columnIndex: int, property: int): void;
      /** Sets whether the designated column is a signed number. */
      setSigned(columnIndex: int, property: boolean): void;
      /** Sets the designated column's normal maximum width in chars. */
      setColumnDisplaySize(columnIndex: int, size: int): void;
      /** Sets the suggested column title for use in printouts and displays. */
      setColumnLabel(columnIndex: int, label: java.lang.String): void;
      /** Sets the name of the designated column. */
      setColumnName(columnIndex: int, columnName: java.lang.String): void;
      /** Sets the name of the designated column's table's schema. */
      setSchemaName(columnIndex: int, schemaName: java.lang.String): void;
      /** Sets the designated column's number of decimal digits. */
      setPrecision(columnIndex: int, precision: int): void;
      /** Sets the designated column's number of digits to the right of the decimal point. */
      setScale(columnIndex: int, scale: int): void;
      /** Sets the designated column's table name. */
      setTableName(columnIndex: int, tableName: java.lang.String): void;
      /** Sets the designated column's table's catalog name. */
      setCatalogName(columnIndex: int, catalogName: java.lang.String): void;
      /** Sets the designated column's SQL type. */
      setColumnType(columnIndex: int, SQLType: int): void;
      /** Sets the designated column's type name. */
      setColumnTypeName(columnIndex: int, typeName: java.lang.String): void;
    }
  }
}

declare namespace java {
  namespace sql {
    namespace rowset {
      /**
       * The interface that all implementations of CachedRowSet must implement.
       * A CachedRowSet object is a container for rows of data that caches its rows in memory.
       */
      interface CachedRowSet extends java.sql.ResultSet {
        /** Moves the cursor to the given row number in this ResultSet object. */
        absolute(row: int): boolean;

        /** Moves the cursor to the first row in this ResultSet object. */
        first(): boolean;

        /** Moves the cursor to the last row in this ResultSet object. */
        last(): boolean;

        /** Moves the cursor to the front of this ResultSet object, just before the first row. */
        beforeFirst(): void;

        /** Moves the cursor to the end of this ResultSet object, just after the last row. */
        afterLast(): void;

        /** Retrieves the number of rows in this CachedRowSet object. */
        size(): int;
      }
    }
  }
}
